export const people = [
  {
    id: 1,
    first_name: "Alia",
    last_name: "Cornick",
    email: "acornick0@stanford.edu",
    gender: "Female",
    phone_number: "520-815-5423",
    discount: 77,
  },
  {
    id: 2,
    first_name: "Ferrell",
    last_name: "Hackforth",
    email: "fhackforth1@google.de",
    gender: "Male",
    phone_number: "877-568-4390",
    discount: 76,
  },
  {
    id: 3,
    first_name: "Joannes",
    last_name: "McMillian",
    email: "jmcmillian2@slate.com",
    gender: "Female",
    phone_number: "157-560-5328",
    discount: 59,
  },
  {
    id: 4,
    first_name: "Nikoletta",
    last_name: "Vallentine",
    email: "nvallentine3@goo.gl",
    gender: "Female",
    phone_number: "563-314-1808",
    discount: 71,
  },
  {
    id: 5,
    first_name: "Mathe",
    last_name: "Durie",
    email: "mdurie4@exblog.jp",
    gender: "Male",
    phone_number: "419-730-8936",
    discount: 8,
  },
  {
    id: 6,
    first_name: "Sophronia",
    last_name: "Chetwin",
    email: "schetwin5@sun.com",
    gender: "Female",
    phone_number: "303-647-3417",
    discount: 76,
  },
  {
    id: 7,
    first_name: "Thoma",
    last_name: "O'Cosgra",
    email: "tocosgra6@admin.ch",
    gender: "Male",
    phone_number: "376-523-9405",
    discount: 23,
  },
  {
    id: 8,
    first_name: "Cash",
    last_name: "Itzhak",
    email: "citzhak7@merriam-webster.com",
    gender: "Male",
    phone_number: "906-713-6364",
    discount: 92,
  },
  {
    id: 9,
    first_name: "Zoe",
    last_name: "Pilbury",
    email: "zpilbury8@alexa.com",
    gender: "Female",
    phone_number: "903-898-7306",
    discount: 8,
  },
  {
    id: 10,
    first_name: "Gerald",
    last_name: "Bartleet",
    email: "gbartleet9@ifeng.com",
    gender: "Non-binary",
    phone_number: "596-598-6581",
    discount: 79,
  },
  {
    id: 11,
    first_name: "Lenora",
    last_name: "Gallego",
    email: "lgallegoa@wunderground.com",
    gender: "Female",
    phone_number: "413-410-9444",
    discount: 99,
  },
  {
    id: 12,
    first_name: "Tore",
    last_name: "Waldram",
    email: "twaldramb@unc.edu",
    gender: "Genderfluid",
    phone_number: "943-275-4349",
    discount: 5,
  },
  {
    id: 13,
    first_name: "Anna-diana",
    last_name: "Caw",
    email: "acawc@rakuten.co.jp",
    gender: "Female",
    phone_number: "866-523-6066",
    discount: 74,
  },
  {
    id: 14,
    first_name: "Davidde",
    last_name: "Hawksworth",
    email: "dhawksworthd@w3.org",
    gender: "Male",
    phone_number: "258-502-2164",
    discount: 44,
  },
  {
    id: 15,
    first_name: "Guillema",
    last_name: "Lung",
    email: "glunge@wiley.com",
    gender: "Female",
    phone_number: "980-269-4513",
    discount: 72,
  },
  {
    id: 16,
    first_name: "Nickolas",
    last_name: "Paradis",
    email: "nparadisf@scientificamerican.com",
    gender: "Male",
    phone_number: "183-708-0663",
    discount: 59,
  },
  {
    id: 17,
    first_name: "Antone",
    last_name: "Troth",
    email: "atrothg@ehow.com",
    gender: "Male",
    phone_number: "241-689-8844",
    discount: 17,
  },
  {
    id: 18,
    first_name: "Marcelline",
    last_name: "Buffey",
    email: "mbuffeyh@macromedia.com",
    gender: "Female",
    phone_number: "868-769-9478",
    discount: 64,
  },
  {
    id: 19,
    first_name: "Rorie",
    last_name: "Lowndsbrough",
    email: "rlowndsbroughi@newyorker.com",
    gender: "Female",
    phone_number: "588-226-0940",
    discount: 74,
  },
  {
    id: 20,
    first_name: "Oralie",
    last_name: "Windaybank",
    email: "owindaybankj@ucla.edu",
    gender: "Female",
    phone_number: "376-859-7628",
    discount: 12,
  },
  {
    id: 21,
    first_name: "Guillema",
    last_name: "Worters",
    email: "gwortersk@simplemachines.org",
    gender: "Female",
    phone_number: "925-467-6282",
    discount: 5,
  },
  {
    id: 22,
    first_name: "Lindi",
    last_name: "Goodall",
    email: "lgoodalll@cisco.com",
    gender: "Female",
    phone_number: "626-555-6870",
    discount: 62,
  },
  {
    id: 23,
    first_name: "Kendre",
    last_name: "Josephson",
    email: "kjosephsonm@flavors.me",
    gender: "Female",
    phone_number: "843-163-7548",
    discount: 87,
  },
  {
    id: 24,
    first_name: "Rog",
    last_name: "McGloughlin",
    email: "rmcgloughlinn@meetup.com",
    gender: "Male",
    phone_number: "139-276-7387",
    discount: 99,
  },
  {
    id: 25,
    first_name: "Jere",
    last_name: "Oxby",
    email: "joxbyo@weebly.com",
    gender: "Male",
    phone_number: "746-139-6047",
    discount: 56,
  },
  {
    id: 26,
    first_name: "Karlotte",
    last_name: "Tarren",
    email: "ktarrenp@cmu.edu",
    gender: "Female",
    phone_number: "816-868-8945",
    discount: 47,
  },
  {
    id: 27,
    first_name: "Aloysius",
    last_name: "Stockey",
    email: "astockeyq@about.com",
    gender: "Male",
    phone_number: "954-822-0093",
    discount: 29,
  },
  {
    id: 28,
    first_name: "Valenka",
    last_name: "Spadaro",
    email: "vspadaror@booking.com",
    gender: "Female",
    phone_number: "493-456-8374",
    discount: 100,
  },
  {
    id: 29,
    first_name: "Malynda",
    last_name: "Sally",
    email: "msallys@slate.com",
    gender: "Bigender",
    phone_number: "534-418-9540",
    discount: 99,
  },
  {
    id: 30,
    first_name: "Lorenzo",
    last_name: "Trimmill",
    email: "ltrimmillt@npr.org",
    gender: "Male",
    phone_number: "862-781-8434",
    discount: 59,
  },
  {
    id: 31,
    first_name: "Perle",
    last_name: "Chavrin",
    email: "pchavrinu@squidoo.com",
    gender: "Female",
    phone_number: "992-309-4372",
    discount: 50,
  },
  {
    id: 32,
    first_name: "Fanchon",
    last_name: "Ensten",
    email: "fenstenv@rakuten.co.jp",
    gender: "Female",
    phone_number: "214-251-7205",
    discount: 78,
  },
  {
    id: 33,
    first_name: "Odelle",
    last_name: "Jansson",
    email: "ojanssonw@mashable.com",
    gender: "Female",
    phone_number: "414-369-2544",
    discount: 24,
  },
  {
    id: 34,
    first_name: "Lorianne",
    last_name: "Essery",
    email: "lesseryx@ucsd.edu",
    gender: "Female",
    phone_number: "753-544-2890",
    discount: 7,
  },
  {
    id: 35,
    first_name: "Farica",
    last_name: "Loins",
    email: "floinsy@hhs.gov",
    gender: "Female",
    phone_number: "981-811-7169",
    discount: 1,
  },
  {
    id: 36,
    first_name: "Lynett",
    last_name: "Bevington",
    email: "lbevingtonz@vkontakte.ru",
    gender: "Female",
    phone_number: "112-954-2675",
    discount: 41,
  },
  {
    id: 37,
    first_name: "Marjy",
    last_name: "Sine",
    email: "msine10@mac.com",
    gender: "Female",
    phone_number: "158-215-2579",
    discount: 29,
  },
  {
    id: 38,
    first_name: "Burgess",
    last_name: "Thunderchief",
    email: "bthunderchief11@yolasite.com",
    gender: "Male",
    phone_number: "984-754-9620",
    discount: 25,
  },
  {
    id: 39,
    first_name: "Carie",
    last_name: "Aasaf",
    email: "caasaf12@cbslocal.com",
    gender: "Female",
    phone_number: "152-335-8091",
    discount: 46,
  },
  {
    id: 40,
    first_name: "Mozelle",
    last_name: "Loache",
    email: "mloache13@surveymonkey.com",
    gender: "Genderqueer",
    phone_number: "530-878-8709",
    discount: 74,
  },
  {
    id: 41,
    first_name: "Cyrillus",
    last_name: "Pennetta",
    email: "cpennetta14@sohu.com",
    gender: "Male",
    phone_number: "487-782-8998",
    discount: 25,
  },
  {
    id: 42,
    first_name: "Imogene",
    last_name: "Giscken",
    email: "igiscken15@51.la",
    gender: "Female",
    phone_number: "177-909-0137",
    discount: 16,
  },
  {
    id: 43,
    first_name: "Gard",
    last_name: "Kentish",
    email: "gkentish16@amazon.de",
    gender: "Male",
    phone_number: "661-899-5553",
    discount: 96,
  },
  {
    id: 44,
    first_name: "Myrtle",
    last_name: "Muttitt",
    email: "mmuttitt17@geocities.jp",
    gender: "Female",
    phone_number: "764-288-6108",
    discount: 78,
  },
  {
    id: 45,
    first_name: "Shana",
    last_name: "Dallicoat",
    email: "sdallicoat18@guardian.co.uk",
    gender: "Female",
    phone_number: "529-230-0863",
    discount: 67,
  },
  {
    id: 46,
    first_name: "Jeane",
    last_name: "Huyghe",
    email: "jhuyghe19@about.me",
    gender: "Female",
    phone_number: "426-223-0164",
    discount: 66,
  },
  {
    id: 47,
    first_name: "Gnni",
    last_name: "Charrisson",
    email: "gcharrisson1a@tinyurl.com",
    gender: "Female",
    phone_number: "903-747-9860",
    discount: 18,
  },
  {
    id: 48,
    first_name: "Izaak",
    last_name: "Enright",
    email: "ienright1b@hubpages.com",
    gender: "Male",
    phone_number: "172-312-6728",
    discount: 11,
  },
  {
    id: 49,
    first_name: "Maren",
    last_name: "Bratcher",
    email: "mbratcher1c@bing.com",
    gender: "Female",
    phone_number: "387-653-3843",
    discount: 1,
  },
  {
    id: 50,
    first_name: "Bibi",
    last_name: "Frusher",
    email: "bfrusher1d@home.pl",
    gender: "Female",
    phone_number: "139-115-4853",
    discount: 69,
  },
  {
    id: 51,
    first_name: "Malynda",
    last_name: "Bracegirdle",
    email: "mbracegirdle1e@dailymotion.com",
    gender: "Female",
    phone_number: "768-553-3624",
    discount: 35,
  },
  {
    id: 52,
    first_name: "Jo-ann",
    last_name: "Cush",
    email: "jcush1f@photobucket.com",
    gender: "Female",
    phone_number: "522-630-0659",
    discount: 82,
  },
  {
    id: 53,
    first_name: "Mabel",
    last_name: "Wilmott",
    email: "mwilmott1g@psu.edu",
    gender: "Female",
    phone_number: "991-610-4826",
    discount: 90,
  },
  {
    id: 54,
    first_name: "Bartel",
    last_name: "Dahl",
    email: "bdahl1h@youtu.be",
    gender: "Male",
    phone_number: "259-341-8176",
    discount: 25,
  },
  {
    id: 55,
    first_name: "Ara",
    last_name: "Sannes",
    email: "asannes1i@mozilla.org",
    gender: "Female",
    phone_number: "118-859-9886",
    discount: 94,
  },
  {
    id: 56,
    first_name: "Trescha",
    last_name: "Colin",
    email: "tcolin1j@independent.co.uk",
    gender: "Female",
    phone_number: "141-495-6783",
    discount: 46,
  },
  {
    id: 57,
    first_name: "Baxy",
    last_name: "Daveren",
    email: "bdaveren1k@bbc.co.uk",
    gender: "Male",
    phone_number: "407-222-7074",
    discount: 12,
  },
  {
    id: 58,
    first_name: "August",
    last_name: "Leel",
    email: "aleel1l@last.fm",
    gender: "Male",
    phone_number: "392-900-1532",
    discount: 85,
  },
  {
    id: 59,
    first_name: "Reed",
    last_name: "Assante",
    email: "rassante1m@alexa.com",
    gender: "Male",
    phone_number: "311-310-4462",
    discount: 18,
  },
  {
    id: 60,
    first_name: "Stillmann",
    last_name: "Somerset",
    email: "ssomerset1n@ovh.net",
    gender: "Male",
    phone_number: "959-682-3796",
    discount: 23,
  },
  {
    id: 61,
    first_name: "Linnie",
    last_name: "Holtham",
    email: "lholtham1o@webmd.com",
    gender: "Female",
    phone_number: "418-924-9440",
    discount: 77,
  },
  {
    id: 62,
    first_name: "Aimil",
    last_name: "Jullian",
    email: "ajullian1p@fda.gov",
    gender: "Female",
    phone_number: "213-285-8822",
    discount: 4,
  },
  {
    id: 63,
    first_name: "Louisette",
    last_name: "MacFarlane",
    email: "lmacfarlane1q@aboutads.info",
    gender: "Polygender",
    phone_number: "232-503-3880",
    discount: 49,
  },
  {
    id: 64,
    first_name: "Deanna",
    last_name: "Matyukon",
    email: "dmatyukon1r@privacy.gov.au",
    gender: "Female",
    phone_number: "896-711-0199",
    discount: 47,
  },
  {
    id: 65,
    first_name: "Blondelle",
    last_name: "Cornilli",
    email: "bcornilli1s@ow.ly",
    gender: "Female",
    phone_number: "241-497-7322",
    discount: 13,
  },
  {
    id: 66,
    first_name: "Eziechiele",
    last_name: "Ghidelli",
    email: "eghidelli1t@samsung.com",
    gender: "Male",
    phone_number: "189-295-7303",
    discount: 23,
  },
  {
    id: 67,
    first_name: "Janean",
    last_name: "McWhorter",
    email: "jmcwhorter1u@businessweek.com",
    gender: "Female",
    phone_number: "118-654-5901",
    discount: 99,
  },
  {
    id: 68,
    first_name: "Herminia",
    last_name: "Figg",
    email: "hfigg1v@github.io",
    gender: "Female",
    phone_number: "643-615-9711",
    discount: 73,
  },
  {
    id: 69,
    first_name: "Cyb",
    last_name: "Jorge",
    email: "cjorge1w@amazon.de",
    gender: "Female",
    phone_number: "240-774-8088",
    discount: 89,
  },
  {
    id: 70,
    first_name: "Cordula",
    last_name: "Gueny",
    email: "cgueny1x@mtv.com",
    gender: "Female",
    phone_number: "224-867-4232",
    discount: 12,
  },
  {
    id: 71,
    first_name: "Sayres",
    last_name: "Swatland",
    email: "sswatland1y@npr.org",
    gender: "Male",
    phone_number: "452-250-7028",
    discount: 88,
  },
  {
    id: 72,
    first_name: "Reggi",
    last_name: "Dunnet",
    email: "rdunnet1z@nasa.gov",
    gender: "Female",
    phone_number: "185-626-4088",
    discount: 12,
  },
  {
    id: 73,
    first_name: "Letty",
    last_name: "Hebard",
    email: "lhebard20@bandcamp.com",
    gender: "Female",
    phone_number: "696-920-9819",
    discount: 81,
  },
  {
    id: 74,
    first_name: "Mitchael",
    last_name: "Burston",
    email: "mburston21@webeden.co.uk",
    gender: "Male",
    phone_number: "418-343-6134",
    discount: 48,
  },
  {
    id: 75,
    first_name: "Wanids",
    last_name: "Bearblock",
    email: "wbearblock22@smh.com.au",
    gender: "Female",
    phone_number: "599-985-7010",
    discount: 9,
  },
  {
    id: 76,
    first_name: "Virgie",
    last_name: "Sanper",
    email: "vsanper23@hud.gov",
    gender: "Male",
    phone_number: "156-591-4984",
    discount: 90,
  },
  {
    id: 77,
    first_name: "Rabi",
    last_name: "Gairdner",
    email: "rgairdner24@gmpg.org",
    gender: "Male",
    phone_number: "404-667-7699",
    discount: 66,
  },
  {
    id: 78,
    first_name: "Bel",
    last_name: "Stummeyer",
    email: "bstummeyer25@tumblr.com",
    gender: "Female",
    phone_number: "260-946-3012",
    discount: 17,
  },
  {
    id: 79,
    first_name: "Lindsey",
    last_name: "Walker",
    email: "lwalker26@techcrunch.com",
    gender: "Male",
    phone_number: "806-288-7204",
    discount: 61,
  },
  {
    id: 80,
    first_name: "Amery",
    last_name: "Klimczak",
    email: "aklimczak27@hubpages.com",
    gender: "Male",
    phone_number: "417-333-8545",
    discount: 13,
  },
  {
    id: 81,
    first_name: "Farica",
    last_name: "Peggram",
    email: "fpeggram28@w3.org",
    gender: "Female",
    phone_number: "456-251-3851",
    discount: 20,
  },
  {
    id: 82,
    first_name: "Maudie",
    last_name: "Buten",
    email: "mbuten29@twitter.com",
    gender: "Genderfluid",
    phone_number: "925-111-3811",
    discount: 93,
  },
  {
    id: 83,
    first_name: "Calv",
    last_name: "Stickler",
    email: "cstickler2a@msn.com",
    gender: "Male",
    phone_number: "993-824-8077",
    discount: 73,
  },
  {
    id: 84,
    first_name: "Aloysia",
    last_name: "Vellender",
    email: "avellender2b@unicef.org",
    gender: "Female",
    phone_number: "369-423-9537",
    discount: 77,
  },
  {
    id: 85,
    first_name: "Carolan",
    last_name: "Beaty",
    email: "cbeaty2c@google.pl",
    gender: "Female",
    phone_number: "680-903-3804",
    discount: 45,
  },
  {
    id: 86,
    first_name: "Towny",
    last_name: "MacKonochie",
    email: "tmackonochie2d@globo.com",
    gender: "Male",
    phone_number: "395-785-7885",
    discount: 93,
  },
  {
    id: 87,
    first_name: "Vincent",
    last_name: "Conan",
    email: "vconan2e@ted.com",
    gender: "Male",
    phone_number: "109-651-4074",
    discount: 74,
  },
  {
    id: 88,
    first_name: "Hilario",
    last_name: "Ebbings",
    email: "hebbings2f@reference.com",
    gender: "Male",
    phone_number: "530-611-6870",
    discount: 27,
  },
  {
    id: 89,
    first_name: "Nealon",
    last_name: "Wolffers",
    email: "nwolffers2g@seesaa.net",
    gender: "Male",
    phone_number: "214-343-6606",
    discount: 14,
  },
  {
    id: 90,
    first_name: "Gale",
    last_name: "Cesco",
    email: "gcesco2h@patch.com",
    gender: "Male",
    phone_number: "676-202-4275",
    discount: 2,
  },
  {
    id: 91,
    first_name: "Pail",
    last_name: "Steeples",
    email: "psteeples2i@google.co.uk",
    gender: "Male",
    phone_number: "633-644-2479",
    discount: 40,
  },
  {
    id: 92,
    first_name: "Perry",
    last_name: "Phelipeaux",
    email: "pphelipeaux2j@youku.com",
    gender: "Non-binary",
    phone_number: "552-660-1312",
    discount: 3,
  },
  {
    id: 93,
    first_name: "Britney",
    last_name: "Dunley",
    email: "bdunley2k@ycombinator.com",
    gender: "Female",
    phone_number: "666-603-0887",
    discount: 36,
  },
  {
    id: 94,
    first_name: "Guillaume",
    last_name: "Yoxall",
    email: "gyoxall2l@eventbrite.com",
    gender: "Male",
    phone_number: "840-409-7028",
    discount: 93,
  },
  {
    id: 95,
    first_name: "Betty",
    last_name: "Leinthall",
    email: "bleinthall2m@bigcartel.com",
    gender: "Female",
    phone_number: "932-235-8055",
    discount: 8,
  },
  {
    id: 96,
    first_name: "Hannis",
    last_name: "Eefting",
    email: "heefting2n@telegraph.co.uk",
    gender: "Female",
    phone_number: "612-776-9338",
    discount: 3,
  },
  {
    id: 97,
    first_name: "Eugen",
    last_name: "Gimblett",
    email: "egimblett2o@wikipedia.org",
    gender: "Male",
    phone_number: "502-345-1258",
    discount: 90,
  },
  {
    id: 98,
    first_name: "Orran",
    last_name: "Mayall",
    email: "omayall2p@tinypic.com",
    gender: "Male",
    phone_number: "867-771-7704",
    discount: 4,
  },
  {
    id: 99,
    first_name: "Isadore",
    last_name: "Magor",
    email: "imagor2q@pagesperso-orange.fr",
    gender: "Male",
    phone_number: "802-387-8209",
    discount: 77,
  },
  {
    id: 100,
    first_name: "Ddene",
    last_name: "Perrelle",
    email: "dperrelle2r@goo.ne.jp",
    gender: "Female",
    phone_number: "735-200-3272",
    discount: 63,
  },
];

export type Customer = (typeof people)[number];
