export const people = [
  {
    first_name: "Agustin",
    last_name: "Pakes",
    email: "apakes0@salon.com",
    gender: "Male",
    phone_number: "(297) 9625779",
    discount: 7,
  },
  {
    first_name: "Halsy",
    last_name: "Huniwall",
    email: "hhuniwall1@japanpost.jp",
    gender: "Male",
    phone_number: "(525) 1612223",
    discount: 19,
  },
  {
    first_name: "Saxe",
    last_name: "Getsham",
    email: "sgetsham2@exblog.jp",
    gender: "Male",
    phone_number: "(291) 3678107",
    discount: 16,
  },
  {
    first_name: "Abelard",
    last_name: "Loudwell",
    email: "aloudwell3@archive.org",
    gender: "Male",
    phone_number: "(135) 2825659",
    discount: 12,
  },
  {
    first_name: "Katharine",
    last_name: "Chippindale",
    email: "kchippindale4@fastcompany.com",
    gender: "Female",
    phone_number: "(123) 2894029",
    discount: 19,
  },
  {
    first_name: "Ramona",
    last_name: "Perazzo",
    email: "rperazzo5@eventbrite.com",
    gender: "Non-binary",
    phone_number: "(224) 9453836",
    discount: 12,
  },
  {
    first_name: "Grantham",
    last_name: "Loblie",
    email: "globlie6@cnn.com",
    gender: "Male",
    phone_number: "(662) 6134302",
    discount: 14,
  },
  {
    first_name: "Weider",
    last_name: "Caddens",
    email: "wcaddens7@ox.ac.uk",
    gender: "Male",
    phone_number: "(978) 6088597",
    discount: 19,
  },
  {
    first_name: "Magdaia",
    last_name: "Bowler",
    email: "mbowler8@google.com",
    gender: "Female",
    phone_number: "(259) 3764855",
    discount: 11,
  },
  {
    first_name: "Zebulen",
    last_name: "Pawlett",
    email: "zpawlett9@goo.gl",
    gender: "Male",
    phone_number: "(852) 6448983",
    discount: 8,
  },
  {
    first_name: "Maurita",
    last_name: "Bartoszewicz",
    email: "mbartoszewicza@1688.com",
    gender: "Female",
    phone_number: "(744) 3520620",
    discount: 13,
  },
  {
    first_name: "Mack",
    last_name: "McCaughren",
    email: "mmccaughrenb@gmpg.org",
    gender: "Male",
    phone_number: "(272) 1281935",
    discount: 8,
  },
  {
    first_name: "Brear",
    last_name: "Stivey",
    email: "bstiveyc@weibo.com",
    gender: "Female",
    phone_number: "(825) 6700374",
    discount: 19,
  },
  {
    first_name: "Rosette",
    last_name: "Sara",
    email: "rsarad@trellian.com",
    gender: "Genderfluid",
    phone_number: "(669) 5450438",
    discount: 2,
  },
  {
    first_name: "Gilbertine",
    last_name: "Burndred",
    email: "gburndrede@ibm.com",
    gender: "Female",
    phone_number: "(682) 9059443",
    discount: 18,
  },
  {
    first_name: "Alexandrina",
    last_name: "Ledster",
    email: "aledsterf@fotki.com",
    gender: "Female",
    phone_number: "(131) 7998959",
    discount: 1,
  },
  {
    first_name: "Grace",
    last_name: "Robker",
    email: "grobkerg@indiatimes.com",
    gender: "Female",
    phone_number: "(242) 7209408",
    discount: 17,
  },
  {
    first_name: "Celestine",
    last_name: "Lafaye",
    email: "clafayeh@people.com.cn",
    gender: "Female",
    phone_number: "(648) 7711133",
    discount: 2,
  },
  {
    first_name: "Wheeler",
    last_name: "Kiggel",
    email: "wkiggeli@utexas.edu",
    gender: "Male",
    phone_number: "(620) 4634814",
    discount: 14,
  },
  {
    first_name: "Ryan",
    last_name: "Lumby",
    email: "rlumbyj@trellian.com",
    gender: "Male",
    phone_number: "(318) 5375006",
    discount: 11,
  },
  {
    first_name: "Noel",
    last_name: "Joerning",
    email: "njoerningk@ebay.com",
    gender: "Male",
    phone_number: "(431) 8138127",
    discount: 6,
  },
  {
    first_name: "Edlin",
    last_name: "Giller",
    email: "egillerl@booking.com",
    gender: "Male",
    phone_number: "(651) 1614902",
    discount: 17,
  },
  {
    first_name: "Charin",
    last_name: "Di Dello",
    email: "cdidellom@howstuffworks.com",
    gender: "Non-binary",
    phone_number: "(146) 1336233",
    discount: 18,
  },
  {
    first_name: "Gertie",
    last_name: "MacCague",
    email: "gmaccaguen@exblog.jp",
    gender: "Genderqueer",
    phone_number: "(283) 7129309",
    discount: 7,
  },
  {
    first_name: "Nicoline",
    last_name: "Devonside",
    email: "ndevonsideo@123-reg.co.uk",
    gender: "Female",
    phone_number: "(382) 8863993",
    discount: 5,
  },
  {
    first_name: "Legra",
    last_name: "Juorio",
    email: "ljuoriop@usa.gov",
    gender: "Female",
    phone_number: "(811) 1347344",
    discount: 0,
  },
  {
    first_name: "Dagmar",
    last_name: "Yeats",
    email: "dyeatsq@meetup.com",
    gender: "Female",
    phone_number: "(788) 1422400",
    discount: 13,
  },
  {
    first_name: "Alvis",
    last_name: "Kenningley",
    email: "akenningleyr@last.fm",
    gender: "Male",
    phone_number: "(863) 2985114",
    discount: 15,
  },
  {
    first_name: "Andie",
    last_name: "Rozycki",
    email: "arozyckis@amazon.co.jp",
    gender: "Female",
    phone_number: "(956) 3878221",
    discount: 19,
  },
  {
    first_name: "Wheeler",
    last_name: "Casaccia",
    email: "wcasacciat@ibm.com",
    gender: "Male",
    phone_number: "(906) 1155039",
    discount: 10,
  },
  {
    first_name: "Farris",
    last_name: "Matyatin",
    email: "fmatyatinu@google.de",
    gender: "Male",
    phone_number: "(728) 2788114",
    discount: 4,
  },
  {
    first_name: "Lillis",
    last_name: "Woolfitt",
    email: "lwoolfittv@facebook.com",
    gender: "Female",
    phone_number: "(110) 4933812",
    discount: 9,
  },
  {
    first_name: "Caroline",
    last_name: "Luck",
    email: "cluckw@chronoengine.com",
    gender: "Female",
    phone_number: "(901) 6101700",
    discount: 6,
  },
  {
    first_name: "Hedwiga",
    last_name: "Kell",
    email: "hkellx@adobe.com",
    gender: "Female",
    phone_number: "(249) 7269572",
    discount: 9,
  },
  {
    first_name: "Ciro",
    last_name: "Bumfrey",
    email: "cbumfreyy@google.it",
    gender: "Male",
    phone_number: "(721) 9479908",
    discount: 19,
  },
  {
    first_name: "Margaux",
    last_name: "Paule",
    email: "mpaulez@stanford.edu",
    gender: "Female",
    phone_number: "(403) 6844124",
    discount: 18,
  },
  {
    first_name: "Balduin",
    last_name: "MacQuist",
    email: "bmacquist10@marketwatch.com",
    gender: "Male",
    phone_number: "(875) 4655636",
    discount: 2,
  },
  {
    first_name: "Tamra",
    last_name: "Staning",
    email: "tstaning11@cnet.com",
    gender: "Female",
    phone_number: "(414) 8710880",
    discount: 6,
  },
  {
    first_name: "Sigismund",
    last_name: "Loughlan",
    email: "sloughlan12@bbb.org",
    gender: "Male",
    phone_number: "(167) 4106582",
    discount: 12,
  },
  {
    first_name: "Brit",
    last_name: "Littley",
    email: "blittley13@facebook.com",
    gender: "Genderqueer",
    phone_number: "(378) 6373043",
    discount: 10,
  },
  {
    first_name: "Immanuel",
    last_name: "Azema",
    email: "iazema14@naver.com",
    gender: "Male",
    phone_number: "(502) 8447504",
    discount: 18,
  },
  {
    first_name: "Graig",
    last_name: "Pinnigar",
    email: "gpinnigar15@walmart.com",
    gender: "Male",
    phone_number: "(603) 1595421",
    discount: 13,
  },
  {
    first_name: "Gardener",
    last_name: "Floch",
    email: "gfloch16@wikipedia.org",
    gender: "Male",
    phone_number: "(668) 1225114",
    discount: 3,
  },
  {
    first_name: "Doro",
    last_name: "Pleavin",
    email: "dpleavin17@devhub.com",
    gender: "Female",
    phone_number: "(420) 1235648",
    discount: 11,
  },
  {
    first_name: "Hailee",
    last_name: "Klement",
    email: "hklement18@squarespace.com",
    gender: "Polygender",
    phone_number: "(982) 1451265",
    discount: 11,
  },
  {
    first_name: "Davey",
    last_name: "Francescuccio",
    email: "dfrancescuccio19@princeton.edu",
    gender: "Male",
    phone_number: "(813) 4168282",
    discount: 16,
  },
  {
    first_name: "Jerald",
    last_name: "Viles",
    email: "jviles1a@weibo.com",
    gender: "Male",
    phone_number: "(428) 2633229",
    discount: 9,
  },
  {
    first_name: "Adora",
    last_name: "Parkisson",
    email: "aparkisson1b@time.com",
    gender: "Female",
    phone_number: "(650) 1200692",
    discount: 12,
  },
  {
    first_name: "Janean",
    last_name: "Bowshire",
    email: "jbowshire1c@technorati.com",
    gender: "Female",
    phone_number: "(239) 8807618",
    discount: 4,
  },
  {
    first_name: "Harlen",
    last_name: "Gilleon",
    email: "hgilleon1d@mysql.com",
    gender: "Male",
    phone_number: "(788) 3227190",
    discount: 12,
  },
  {
    first_name: "Arlana",
    last_name: "Luddy",
    email: "aluddy1e@bbb.org",
    gender: "Female",
    phone_number: "(789) 7854528",
    discount: 11,
  },
  {
    first_name: "Tomaso",
    last_name: "Gidney",
    email: "tgidney1f@oracle.com",
    gender: "Male",
    phone_number: "(618) 4847022",
    discount: 5,
  },
  {
    first_name: "Gerti",
    last_name: "Poytheras",
    email: "gpoytheras1g@ucsd.edu",
    gender: "Female",
    phone_number: "(784) 5333270",
    discount: 17,
  },
  {
    first_name: "Gordan",
    last_name: "Cottam",
    email: "gcottam1h@amazon.de",
    gender: "Male",
    phone_number: "(396) 5740951",
    discount: 6,
  },
  {
    first_name: "Nickie",
    last_name: "Stuchbery",
    email: "nstuchbery1i@ocn.ne.jp",
    gender: "Agender",
    phone_number: "(957) 2910690",
    discount: 5,
  },
  {
    first_name: "Jordon",
    last_name: "Sommerlie",
    email: "jsommerlie1j@goo.gl",
    gender: "Male",
    phone_number: "(162) 8941811",
    discount: 13,
  },
  {
    first_name: "Charles",
    last_name: "Celler",
    email: "cceller1k@senate.gov",
    gender: "Male",
    phone_number: "(794) 4001163",
    discount: 12,
  },
  {
    first_name: "Bonnie",
    last_name: "Foulser",
    email: "bfoulser1l@skype.com",
    gender: "Non-binary",
    phone_number: "(354) 6127407",
    discount: 13,
  },
  {
    first_name: "Suzie",
    last_name: "Leven",
    email: "sleven1m@parallels.com",
    gender: "Bigender",
    phone_number: "(230) 2072478",
    discount: 16,
  },
  {
    first_name: "Cosme",
    last_name: "Hearmon",
    email: "chearmon1n@mashable.com",
    gender: "Male",
    phone_number: "(550) 4377220",
    discount: 0,
  },
  {
    first_name: "Carlie",
    last_name: "Cornelius",
    email: "ccornelius1o@engadget.com",
    gender: "Male",
    phone_number: "(921) 2560202",
    discount: 18,
  },
  {
    first_name: "Don",
    last_name: "Kinchington",
    email: "dkinchington1p@constantcontact.com",
    gender: "Male",
    phone_number: "(647) 5451448",
    discount: 11,
  },
  {
    first_name: "Inglebert",
    last_name: "Merioth",
    email: "imerioth1q@jimdo.com",
    gender: "Male",
    phone_number: "(301) 5627034",
    discount: 15,
  },
  {
    first_name: "Kandace",
    last_name: "Lening",
    email: "klening1r@narod.ru",
    gender: "Female",
    phone_number: "(348) 6029741",
    discount: 14,
  },
  {
    first_name: "Meta",
    last_name: "Soame",
    email: "msoame1s@admin.ch",
    gender: "Female",
    phone_number: "(519) 3364947",
    discount: 11,
  },
  {
    first_name: "Jeanne",
    last_name: "Oaker",
    email: "joaker1t@symantec.com",
    gender: "Female",
    phone_number: "(794) 2792795",
    discount: 14,
  },
  {
    first_name: "Katey",
    last_name: "Cosson",
    email: "kcosson1u@pen.io",
    gender: "Female",
    phone_number: "(800) 2386240",
    discount: 8,
  },
  {
    first_name: "Tristam",
    last_name: "Dowzell",
    email: "tdowzell1v@google.de",
    gender: "Male",
    phone_number: "(773) 2824422",
    discount: 8,
  },
  {
    first_name: "Chevalier",
    last_name: "Edmundson",
    email: "cedmundson1w@techcrunch.com",
    gender: "Male",
    phone_number: "(475) 1690518",
    discount: 6,
  },
  {
    first_name: "Urbain",
    last_name: "Bielfeldt",
    email: "ubielfeldt1x@noaa.gov",
    gender: "Male",
    phone_number: "(297) 5366181",
    discount: 1,
  },
  {
    first_name: "Kaycee",
    last_name: "Axon",
    email: "kaxon1y@eventbrite.com",
    gender: "Female",
    phone_number: "(645) 4228872",
    discount: 13,
  },
  {
    first_name: "Elden",
    last_name: "Limbrick",
    email: "elimbrick1z@apache.org",
    gender: "Male",
    phone_number: "(516) 9216276",
    discount: 4,
  },
  {
    first_name: "Perl",
    last_name: "Lowerson",
    email: "plowerson20@rambler.ru",
    gender: "Female",
    phone_number: "(183) 9646378",
    discount: 17,
  },
  {
    first_name: "Caressa",
    last_name: "Youson",
    email: "cyouson21@elpais.com",
    gender: "Female",
    phone_number: "(809) 7170824",
    discount: 20,
  },
  {
    first_name: "Susann",
    last_name: "Fullerlove",
    email: "sfullerlove22@whitehouse.gov",
    gender: "Female",
    phone_number: "(949) 3445715",
    discount: 8,
  },
  {
    first_name: "Phillipp",
    last_name: "Chung",
    email: "pchung23@dot.gov",
    gender: "Male",
    phone_number: "(671) 8980622",
    discount: 17,
  },
  {
    first_name: "Pippy",
    last_name: "Wolpert",
    email: "pwolpert24@posterous.com",
    gender: "Female",
    phone_number: "(478) 6912364",
    discount: 12,
  },
  {
    first_name: "Celisse",
    last_name: "Westgarth",
    email: "cwestgarth25@drupal.org",
    gender: "Female",
    phone_number: "(353) 7430923",
    discount: 7,
  },
  {
    first_name: "Minerva",
    last_name: "Dreakin",
    email: "mdreakin26@odnoklassniki.ru",
    gender: "Agender",
    phone_number: "(222) 9606486",
    discount: 15,
  },
  {
    first_name: "Tabbitha",
    last_name: "Sodor",
    email: "tsodor27@wp.com",
    gender: "Female",
    phone_number: "(590) 4585590",
    discount: 13,
  },
  {
    first_name: "Lola",
    last_name: "Brydone",
    email: "lbrydone28@simplemachines.org",
    gender: "Genderqueer",
    phone_number: "(501) 2607245",
    discount: 11,
  },
  {
    first_name: "Kent",
    last_name: "Marcinkowski",
    email: "kmarcinkowski29@lycos.com",
    gender: "Male",
    phone_number: "(366) 9236598",
    discount: 3,
  },
  {
    first_name: "Harv",
    last_name: "Storah",
    email: "hstorah2a@ezinearticles.com",
    gender: "Male",
    phone_number: "(562) 8948460",
    discount: 15,
  },
  {
    first_name: "Rowena",
    last_name: "Wrintmore",
    email: "rwrintmore2b@tinyurl.com",
    gender: "Female",
    phone_number: "(419) 7286095",
    discount: 1,
  },
  {
    first_name: "Merv",
    last_name: "O'Kielt",
    email: "mokielt2c@surveymonkey.com",
    gender: "Male",
    phone_number: "(147) 3644989",
    discount: 0,
  },
  {
    first_name: "Martelle",
    last_name: "Halhead",
    email: "mhalhead2d@usnews.com",
    gender: "Female",
    phone_number: "(431) 7833498",
    discount: 9,
  },
  {
    first_name: "Lissi",
    last_name: "Da Costa",
    email: "ldacosta2e@google.es",
    gender: "Female",
    phone_number: "(113) 9991610",
    discount: 3,
  },
  {
    first_name: "Timi",
    last_name: "Piechnik",
    email: "tpiechnik2f@google.com",
    gender: "Female",
    phone_number: "(439) 1999414",
    discount: 17,
  },
  {
    first_name: "Kenna",
    last_name: "Tembey",
    email: "ktembey2g@gnu.org",
    gender: "Female",
    phone_number: "(582) 6316471",
    discount: 17,
  },
  {
    first_name: "Fonz",
    last_name: "Blaydon",
    email: "fblaydon2h@fema.gov",
    gender: "Male",
    phone_number: "(914) 9639034",
    discount: 12,
  },
  {
    first_name: "Ilyse",
    last_name: "Drysdall",
    email: "idrysdall2i@phoca.cz",
    gender: "Female",
    phone_number: "(305) 7625449",
    discount: 9,
  },
  {
    first_name: "Honoria",
    last_name: "Moreinu",
    email: "hmoreinu2j@flavors.me",
    gender: "Female",
    phone_number: "(811) 3577719",
    discount: 19,
  },
  {
    first_name: "Brooks",
    last_name: "Bonnesen",
    email: "bbonnesen2k@seesaa.net",
    gender: "Female",
    phone_number: "(851) 7240801",
    discount: 2,
  },
  {
    first_name: "Harmony",
    last_name: "Eleshenar",
    email: "heleshenar2l@exblog.jp",
    gender: "Female",
    phone_number: "(560) 7587461",
    discount: 14,
  },
  {
    first_name: "Lacy",
    last_name: "Glasebrook",
    email: "lglasebrook2m@about.me",
    gender: "Bigender",
    phone_number: "(347) 3137151",
    discount: 20,
  },
  {
    first_name: "Derron",
    last_name: "Gorman",
    email: "dgorman2n@patch.com",
    gender: "Male",
    phone_number: "(713) 6570222",
    discount: 11,
  },
  {
    first_name: "Viviana",
    last_name: "Benedite",
    email: "vbenedite2o@slideshare.net",
    gender: "Female",
    phone_number: "(831) 5328647",
    discount: 5,
  },
  {
    first_name: "Othello",
    last_name: "Kellet",
    email: "okellet2p@reddit.com",
    gender: "Male",
    phone_number: "(419) 8887093",
    discount: 2,
  },
  {
    first_name: "Carl",
    last_name: "Lesley",
    email: "clesley2q@de.vu",
    gender: "Male",
    phone_number: "(221) 4162194",
    discount: 4,
  },
  {
    first_name: "Raff",
    last_name: "Roostan",
    email: "rroostan2r@yolasite.com",
    gender: "Male",
    phone_number: "(756) 4268533",
    discount: 13,
  },
];

export type Customer = (typeof people)[number];
